### ISSUE TITLE
Show valid moves on board when tile is selected

### ISSUE THREAD

**Issue by extrajordanary** [AlexNisnevich/voluspa#4]
After I select a tile to use on the right, it would be nice to colorize or otherwise highlight which squares I can place it on. 

Alternatively you could just have error messages so that I know why a tile isn't placed when I try an invalid move, but I think it's easier to just show people their possible options up front.

Would also be cool if you can see the highlighted tiles even when you are just hovering over the tile, so you can do a quick mouseover to check your options.

**Comment by AlexNisnevich** [comment]
That's a really good idea and probably wouldn't be terribly hard to implement. I'll take a look :-)

**Comment by AlexNisnevich** [comment]
Closed in #8.
